import {test,expect,type Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(()=>(window as any).phieldworks.snapshot());
const qual=(page:Page)=>page.evaluate(()=>(window as any).phieldworks.snapshot().qualifications[0].status);
async function point(page:Page,x:number,y:number){const p=await page.evaluate(([x,y])=>(window as any).phieldworks.screen(x,y),[x,y]);await page.mouse.click(p.x,p.y);}
async function ready(page:Page,skip=true){if(skip)await page.addInitScript(()=>localStorage.setItem('phieldworks.tutorial.v1',JSON.stringify({closed:true,index:0})));await page.goto('/');await expect(page.locator('#runtime-status')).toHaveText('SIMULATION ONLINE');}
test('resources are selectable, categories explain requirements, and backdrop dismisses manual',async({page})=>{await ready(page);await expect(page.locator('#menu')).toContainText('PHIELDWORKS');await point(page,4,18);await expect(page.locator('#inspector')).toContainText('Ferrous deposit');await expect(page.locator('#inspector')).toContainText('900');await page.locator('#extract-deposit').click();await expect(page.locator('#build-requirements')).toContainText('8 electrical power');await page.locator('#catalog-toggle').click();await page.getByRole('tab',{name:'Extraction',exact:true}).click();await expect(page.getByRole('tab',{name:'Extraction',exact:true})).toHaveAttribute('aria-selected','true');await page.locator('#tool-select').click();await page.getByRole('tab',{name:'All',exact:true}).click();await page.locator('#catalog-close').click();await page.locator('#tool-material').click();await expect(page.locator('#tool-material')).toHaveAttribute('aria-pressed','true');await page.locator('#tool-select').click();await page.locator('#menu').click();await page.locator('#session-manual').click();await page.mouse.click(15,15);await expect(page.locator('#manual')).not.toBeVisible();await page.screenshot({path:'test-results/resources-and-terrain.png',fullPage:true});});
test('camera zoom anchors at cursor, minimap pans, and home restores the outpost',async({page})=>{await ready(page);const cam=()=>page.evaluate(()=>(window as any).phieldworks.camera());const initial=await cam();const before=await page.evaluate(()=>(window as any).phieldworks.screen(15,12));await page.mouse.move(before.x,before.y);await page.mouse.wheel(0,-200);await expect.poll(async()=>(await cam()).zoom).toBeGreaterThan(initial.zoom);const after=await page.evaluate(()=>(window as any).phieldworks.screen(15,12));expect(Math.abs(after.x-before.x)).toBeLessThan(1);expect(Math.abs(after.y-before.y)).toBeLessThan(1);await page.locator('#minimap-toggle').click();await page.locator('#minimap').click({position:{x:70,y:40}});expect((await cam()).panX).not.toBe(initial.panX);await page.locator('#home').click();expect(await cam()).toEqual(initial);const afterHome=await cam();await page.locator('#minimap').dblclick({position:{x:30,y:50}});expect((await cam()).panX).not.toBe(afterHome.panX);await page.locator('#home').click();await page.locator('#world').focus();await page.keyboard.press('d');expect((await cam()).panX).toBe(initial.panX-50);await page.locator('#fit-map').click();await page.screenshot({path:'test-results/minimap-full-sector.png',fullPage:true});});
 test('creatures move; sentry requirements and actionable diagnostics work through UI',async({page})=>{await ready(page);const before=(await state(page)).ecology.creatures[0];await expect.poll(async()=>{const c=(await state(page)).ecology.creatures[0];return Math.hypot(c.x-before.x,c.y-before.y);}).toBeGreaterThan(.3);const creature=(await state(page)).ecology.creatures[0];await point(page,creature.x,creature.y);await expect(page.locator('#inspector')).toContainText('Investigating crawler');await page.getByRole('button',{name:'Build Perimeter sentry',exact:true}).click();await point(page,20.1,17.1);await page.locator('#tool-select').click();await page.locator('#issues').click();await expect(page.locator('#active-issues')).toContainText('No electrical power');await page.locator('#active-issues article').filter({hasText:'No electrical power'}).getByRole('button',{name:'Locate & inspect'}).click();await expect(page.locator('#inspector')).toContainText('Perimeter sentry');await page.locator('#close-issues').click();await page.locator('#home').click();await page.locator('#tool-power').click();await point(page,10.5,3);await point(page,21,17);await expect.poll(async()=>(await state(page)).ecology.defenseReady).toBe(true);await page.locator('#menu').click();await page.locator('#session-save').click();await page.locator('#menu').click();await page.locator('#session-load').click();expect((await state(page)).ecology.defenseReady).toBe(true);await page.screenshot({path:'test-results/perimeter-defense.png',fullPage:true});});
test('diagnostics telemetry trend captures live metrics and keeps a report',async({page})=>{await ready(page);await page.locator('#issues').click();await expect(page.locator('#diagnostics-panel')).toBeVisible();await expect(page.locator('#trend-summary')).toContainText('Collecting telemetry');await page.locator('#speed').click();await page.locator('#speed').click();await expect.poll(async()=>page.locator('#trend-summary').textContent(),{timeout:15000}).toContain('samples');await expect(page.locator('#trend-chart path')).toHaveCount(2);await expect(page.locator('#copy-report')).toBeVisible();await page.screenshot({path:'test-results/diagnostics-trends.png',fullPage:true});});
test('first-run tutorial follows real outpost actions and supports skip and replay',async({page})=>{await ready(page,false);await expect(page.locator('#tutorial')).toContainText('guided tour');await page.locator('[data-tutorial=start]').click();await expect(page.locator('#tutorial')).toContainText('Welcome');await page.locator('[data-tutorial=next]').click();await page.locator('#minimap-toggle').click();await page.locator('#zoom-in').click();await expect(page.locator('[data-tutorial=next]')).toBeEnabled();await page.locator('[data-tutorial=next]').click();await page.locator('#home').click();await point(page,4,18);await expect(page.locator('[data-tutorial=next]')).toBeEnabled();await page.locator('[data-tutorial=next]').click();await point(page,4.5,12);await expect(page.locator('[data-tutorial=next]')).toBeEnabled();await page.screenshot({path:'test-results/contextual-onboarding.png',fullPage:true});await page.locator('[data-tutorial=skip]').click();await page.reload();await expect(page.locator('#tutorial')).toBeHidden();await page.locator('#menu').click();await page.locator('#session-tutorial').click();await expect(page.locator('#tutorial')).toContainText('Welcome');});
test('guided outpost reaches commissioning with a powered perimeter defense',async({page})=>{
 await ready(page,false);await page.locator('[data-tutorial=start]').click();const next=async()=>{await expect(page.locator('[data-tutorial=next]')).toBeEnabled();await page.locator('[data-tutorial=next]').click();};
 await next();await page.locator('#minimap-toggle').click();await page.locator('#zoom-in').click();await next();await page.locator('#home').click();await point(page,4,18);await next();await point(page,4.5,12);await next();
 await page.getByRole('button',{name:'Build Perimeter sentry',exact:true}).click();await point(page,22.1,10.1);await page.locator('#tool-power').click();await point(page,10.5,3);await point(page,23,10);await expect.poll(async()=>(await state(page)).ecology.defenseReady).toBe(true);await next();
 await page.getByRole('button',{name:'Build Phase tuner',exact:true}).click();await point(page,17.1,12.1);await next();
 await page.getByRole('button',{name:'Build Field emitter',exact:true}).click();await point(page,20.1,12.1);await page.locator('#tool-power').click();await point(page,10.5,3);await point(page,21.5,12);await next();
 await page.locator('#tool-field').click();await point(page,16,10.5);await point(page,17,12.5);await point(page,19,12.5);await point(page,20,13.5);await next(); await page.locator('#issues').click();await next();await page.locator('#close-issues').click();
 await page.locator('#objective-toggle').click();await page.locator('#controller').check();await page.locator('#speed').click();await page.locator('#speed').click();await expect.poll(async()=>(await state(page)).frontier,{timeout:45000}).toBe(true);await page.locator('#objective-toggle').click();if(await page.locator('#inspector-drawer').isVisible())await page.locator('#close-inspector').click();await next();
 await page.locator('#objective-toggle').click();await page.locator('#commission').click();await expect.poll(async()=>['qualified','failed'].includes(await qual(page)),{timeout:15000}).toBe(true);if((await qual(page))==='failed'){await expect(page.locator('#commission-reason')).toContainText('Wildlife');await expect.poll(async()=>(await state(page)).ecology.creatures.every((c:any)=>c.health<=0),{timeout:15000}).toBe(true);await page.locator('#tool-select').click();for(const e of (await state(page)).entities.filter((e:any)=>e.health<100)){await point(page,e.x+.5,e.y+.5);await page.locator('#repair').click();}if(await page.locator('#inspector-drawer').isVisible())await page.locator('#close-inspector').click();await page.locator('#commission').click();}await expect.poll(async()=>await qual(page),{timeout:15000}).toBe('qualified');await page.locator('#capture').click();await page.locator('#objective-toggle').click();await next();await next();await expect(page.locator('#tutorial')).toBeHidden();expect((await state(page)).entities.every((e:any)=>e.health>0)).toBe(true);await page.screenshot({path:'test-results/guided-qualified-outpost.png',fullPage:true});
});
