import {test} from 'node:test';import assert from 'node:assert/strict';
import {createWorld,place,connect,step,evaluate,entity,setPhase,setController,beginCommission,captureBlueprint,stampBlueprint,serialize,deserialize,remove,repair,placementError,newEntity,DT,MACHINE_LIMIT,FIELD_PORT_LIMIT,DEFS,frontierTarget,frontierQualification,type World} from '../src/sim/world';
export function armedWorld(){const w=createWorld();assert.equal(place(w,'tuner',17,12),'');const t=w.entities.at(-1)!;assert.equal(place(w,'emitter',20,12),'');const e=w.entities.at(-1)!;assert.equal(connect(w,'power',{node:w.entities.find(e=>e.kind==='generator')!.id,port:0},{node:e.id,port:0}),'');const j=w.entities.find(e=>e.kind==='junction')!;assert.equal(connect(w,'field',{node:j.id,port:3},{node:t.id,port:0}),'');assert.equal(connect(w,'field',{node:t.id,port:1},{node:e.id,port:0}),'');evaluate(w);return w;}
const tick=(w:World,seconds:number)=>{for(let i=0;i<seconds/DT;i++)step(w);};
test('starter production conserves ore into assemblies and needs power',()=>{const w=createWorld();const stock=w.stock.assemblies;tick(w,12);assert.ok(w.stock.assemblies>stock);const mined=1400-w.deposits[0].remaining;const buffered=w.entities.reduce((s,e)=>s+e.ore,0);assert.equal(mined,buffered+w.links.reduce((n,l)=>n+l.packets.length,0)+w.produced*2);remove(w,w.entities.find(e=>e.kind==='generator')!.id);const before=w.produced;tick(w,5);assert.equal(w.produced,before);});
test('placement costs are atomic and obstacles/frontier respected',()=>{const w=createWorld(),stock=w.stock.assemblies;assert.ok(place(w,'emitter',10,9));assert.equal(w.stock.assemblies,stock);assert.ok(place(w,'extractor',15,20));assert.ok(place(w,'emitter',28,20));assert.equal(place(w,'tuner',17,12),'');assert.equal(w.stock.assemblies,stock-6);});
test('tuner phase changes useful target power; total field power remains accounted for',()=>{const w=armedWorld(),t=w.entities.find(e=>e.kind==='tuner')!;let min=Infinity,max=0;for(let phase=-180;phase<=180;phase+=5){t.phase=phase;const s=evaluate(w);min=Math.min(min,s.targetPower);max=Math.max(max,s.targetPower);assert.ok(Math.abs(s.network.sourcePower-s.heat-s.radiated-s.network.escaped-s.network.linkLoss)<1e-7);assert.ok(s.targetPower<=s.radiated+1e-8);}assert.ok(max>35,`max ${max}`);assert.ok(min<3,`min ${min}`);});
test('controller clears frontier and passes disturbance commissioning',()=>{const w=armedWorld();setController(w,true);tick(w,90);assert.equal(w.frontier,true);assert.ok(w.stats.targetPower>35);assert.equal(beginCommission(w),'');tick(w,21);const q=frontierQualification(w)!;assert.equal(q.status,'qualified',q.reason);assert.ok(q.minimum>=32);const t=w.entities.find(e=>e.kind==='tuner')!;setPhase(w,t.id,0);assert.equal(frontierQualification(w)!.status,'failed');});
test('qualified blueprint places atomically with fresh IDs and no inherited qualification',()=>{const w=armedWorld();setController(w,true);tick(w,90);beginCommission(w);tick(w,21);assert.equal(captureBlueprint(w),'');const restored=deserialize(serialize(w));assert.equal(restored.blueprint?.entities.length,w.blueprint?.entities.length);assert.equal(frontierQualification(restored)!.status,'stale');w.stock.assemblies=300;const n=w.entities.length,cost=w.stock.assemblies;assert.ok(stampBlueprint(w,3,3));assert.equal(w.entities.length,n);assert.equal(w.stock.assemblies,cost);assert.equal(stampBlueprint(w,38,3),'');assert.equal(w.entities.length,2*n);assert.equal(new Set(w.entities.map(e=>e.id)).size,2*n);assert.equal(frontierQualification(w)!.status,'failed');});
test('thermal protection and bypass have distinct consequences',()=>{const w=createWorld();const d=w.entities.find(e=>e.kind==='dump')!;d.temperature=90;step(w);assert.equal(d.tripped,true);assert.ok(d.health>0);d.protection=false;d.tripped=false;d.temperature=25;w.links=w.links.filter(l=>l.type!=='field');const ref=w.entities.find(e=>e.kind==='reference')!;connect(w,'field',{node:ref.id,port:0},{node:d.id,port:0});tick(w,180);assert.equal(d.health,0);assert.ok(w.stock.scrap>0);assert.equal(repair(w,d.id),'');assert.equal(d.health,100);});
test('save/load restores physical state and rejects corrupt topology and NaNs',()=>{const w=armedWorld();tick(w,5);const loaded=deserialize(serialize(w));assert.equal(loaded.entities.length,w.entities.length);assert.deepEqual(loaded.stock,w.stock);assert.ok(Math.abs(loaded.stats.targetPower-w.stats.targetPower)<1e-8);const s=JSON.parse(serialize(w));s.entities[0].x=-1;assert.throws(()=>deserialize(JSON.stringify(s)),/Invalid/);s.entities[0].x=9;s.links[0].a.node='missing';assert.throws(()=>deserialize(JSON.stringify(s)),/Invalid/);assert.throws(()=>deserialize('{broken'));});
test('unconnected ports leak; reconnecting cannot duplicate routes',()=>{const w=createWorld();assert.ok(w.stats.network.escaped>30);const l=w.links.find(l=>l.type==='field')!;assert.ok(connect(w,'field',l.a,l.b));});

test('fixed steps produce identical outcomes from identical saves',()=>{const a=armedWorld(),b=deserialize(serialize(a));setController(a,true);setController(b,true);tick(a,12);tick(b,12);assert.deepEqual(a.stock,b.stock);assert.equal(frontierTarget(a)!.health,frontierTarget(b)!.health);assert.equal(a.stats.targetPower,b.stats.targetPower);});
test('malformed blueprint and fractional port saves are rejected',()=>{const w=armedWorld(),save=JSON.parse(serialize(w));save.blueprint={entities:[{id:'bad'}],links:[]};assert.throws(()=>deserialize(JSON.stringify(save)),/Invalid/);save.blueprint=null;save.links[1].a.port=0.5;assert.throws(()=>deserialize(JSON.stringify(save)),/Invalid/);});
test('protection redirects live input upstream and cools the protected dump',()=>{const w=createWorld(),d=w.entities.find(e=>e.kind==='dump')!,ref=w.entities.find(e=>e.kind==='reference')!;w.links=w.links.filter(l=>l.type!=='field');connect(w,'field',{node:ref.id,port:0},{node:d.id,port:0});d.temperature=90;step(w);assert.equal(d.tripped,true);assert.ok(w.stats.network.ports[ref.id][0].incoming>0);const before=d.temperature;tick(w,3);assert.ok(d.temperature<before);assert.equal(d.health,100);});
test('prototype machine and field-port caps use the exported limits',()=>{const w=createWorld();const room=MACHINE_LIMIT-w.entities.length;const extras=(n:number)=>Array.from({length:n},(_,i)=>newEntity('sentry',-1000-i,-1000,`e${9000+i}`));assert.equal(placementError(w,'sentry',1,30,extras(room-1)),'');assert.match(placementError(w,'sentry',1,30,extras(room)),new RegExp(String(MACHINE_LIMIT)));const ports=Array.from({length:Math.ceil(FIELD_PORT_LIMIT/4)+1},(_,i)=>newEntity('junction',-2000-i,-2000,`e${9500+i}`));assert.match(placementError(w,'junction',1,30,ports),/field ports/);assert.ok(deserialize(serialize(w)));});
test('the field-port cap is enforced consistently by placement and save load',()=>{const base=createWorld().entities.reduce((n,e)=>n+DEFS[e.kind].ports.length,0);const junctions=(n:number,prefix:number)=>Array.from({length:n},(_,i)=>newEntity('junction',2+(i%16)*2,20+Math.floor(i/16)*2,`e${prefix+i}`));const fit=Math.floor((FIELD_PORT_LIMIT-base-4)/4);const w=createWorld();assert.equal(placementError(w,'junction',1,30,junctions(fit,200)),'');assert.match(placementError(w,'junction',1,30,junctions(fit+1,300)),/field ports/);const n=Math.floor((FIELD_PORT_LIMIT-base)/4);const ok=createWorld();for(const j of junctions(n,400))ok.entities.push(j);assert.doesNotThrow(()=>deserialize(serialize(ok)));const over=createWorld();for(const j of junctions(n+1,500))over.entities.push(j);assert.throws(()=>deserialize(serialize(over)),/Invalid/);});
