import type {World} from '../sim/world';

export type Pack='industrial'|'precision'|'systems';
export interface Technology {
 id:string; name:string; column:number; lane:number; requires:string[];
 kind:'supplied'|'milestone'|'research'|'project';
 summary:string; unlocks:string[]; condition:string; art:string;
 cost?:{units:number;seconds:number;packs:Pack[]};
 observed?:(world:World)=>boolean;
}
export const lanes=['Industry & logistics','Field & control','Power & defense','Materials & fabrication'];
export const stages=['Expedition kit','First frontier','Proven outpost','Research foundation','Industrial branches','Precision foundation','Advanced networks','Systems science','Planetary industry','Launch infrastructure','Final acceptance'];
export const packs:Record<Pack,{name:string;recipe:string;producer:string;unlockedBy:string}>={
 industrial:{name:'Industrial dossier',recipe:'2 assemblies + 1 crystal → 1 dossier / 4 s',producer:'Research workbench',unlockedBy:'research'},
 precision:{name:'Precision dossier',recipe:'1 industrial dossier + 1 control board + 1 polished crystal → 1 dossier / 6 s',producer:'Research workbench',unlockedBy:'precision'},
 systems:{name:'Systems dossier',recipe:'1 precision dossier + 1 photonic module + 1 accepted precision part → 1 dossier / 10 s',producer:'Research workbench',unlockedBy:'photonics'}
};
const n=(id:string,name:string,column:number,lane:number,requires:string[],kind:Technology['kind'],summary:string,unlocks:string[],condition:string,art:string,cost?:Technology['cost'],observed?:Technology['observed']):Technology=>({id,name,column,lane,requires,kind,summary,unlocks,condition,art,cost,observed});
const c=(units:number,seconds:number,...packs:Pack[])=>({units,seconds,packs});
export const technologies:Technology[]=[
 n('outpost','Automated outpost',0,0,[],'supplied','The expedition brings the tools to rebuild its own supply chain.',['Extractor, assembler, power unit','Belts, wires, repair and recovery'],'Included with every expedition.','Extractor drill / assembler arm / generator rotor loops.'),
 n('fieldcraft','Field engineering',0,1,['outpost'],'supplied','Discover how routing and relative phase change useful delivery.',['Reference station, junction, tuner, emitter, cooled dump','Baseline diagnostics and automatic phase control'],'Included with every expedition.','Tuner carriage, emitter gimbal and dump fan loops.'),
 n('perimeter','Perimeter defense',0,2,['outpost'],'supplied','Give the player a defense before field exposure can provoke attacks.',['Wired perimeter sentry','Defense readiness and 30-second grace period'],'Available immediately; wire a sentry to activate the existing defense gate.','Sentry scan / fire and crawler locomotion.'),
 n('frontier','Open the frontier',1,1,['fieldcraft'],'milestone','Concentrate useful power to remove the armored guardian.',['Eastern building area','Access to the crystal deposit'],'Clear the guardian by delivering more than 32 on-target field units.','Guardian armor stress, hit and collapse frames.',undefined,w=>w.frontier),
 n('crystal','First crystal',2,0,['frontier'],'milestone','Make the new territory feed the next industrial tier.',['Crystal supply for research'],'Harvest at least 1 crystal using a powered extractor over the frontier deposit.','Crystal extractor operating accent.',undefined,w=>w.stock.crystal>0),
 n('qualification','Qualified outpost',2,1,['frontier'],'milestone','Finish an engineering experiment with a reusable operating contract.',['Qualified blueprint capture and placement'],'Enable automatic phase control and establish at least 35 target units to start. Sustain at least 32 units for the 20-second drift test with no trips or destroyed equipment, then record a blueprint. Every placed installation needs local qualification.','Reference station acceptance indicator.',undefined,w=>!!w.blueprint),
 n('research','Industrial research',3,0,['crystal','qualification'],'project','Turn surplus production into lasting capabilities.',['Research workbench and laboratory recipes','Industrial dossier recipe','One research queue, shared across powered laboratories'],'First crystal and a qualified blueprint unlock the workbench and laboratory recipes immediately. Build and power these machines to begin pack-funded research; their construction needs no science packs.','Workbench sample arm and laboratory carousel.'),
 n('logistics','Structured logistics',4,0,['research'],'research','Expand material routing without rebuilding every connection.',['Belt splitter and underground crossing','Paid transport segments and segment editing'],'Complete research in powered laboratories.', 'Splitter gate and belt motion.',c(40,10,'industrial')),
 n('instrumentation','Instrumented networks',4,1,['research'],'research','See trends and isolate causes before increasing output.',['Monitor station with time-series traces','Branch probes and diagnostic history export'],'Complete research; baseline errors remain available from the start.','Monitor sweep and probe status.',c(30,10,'industrial')),
 n('grid','Power distribution',4,2,['research'],'research','Supply several production districts with understandable capacity limits.',['Power poles and substations','Multiple generators on a bus; overload isolation'],'Complete research in powered laboratories.','Substation breaker and switch indicators.',c(40,10,'industrial')),
 n('materials','Prepared materials',4,3,['research'],'research','Convert frontier resources into repeatable manufacturing inputs.',['Material processor','Polished crystal: 2 crystal → 1 / 4 s','Steel, copper conductors and ceramic substrates','Control board: 2 assemblies + 2 conductors + 1 ceramic → 1 / 6 s'],'Complete research; build a powered processor to make the new recipes.','Processor feed rollers and polishing head.',c(50,10,'industrial')),
 n('modules','Modular construction',5,0,['logistics','qualification','materials'],'research','Replicate selected production cells with explicit service boundaries.',['Selected-area blueprints','Service connectors and construction requests'],'Complete research; local qualification remains mandatory.','Service connector / construction status markers.',c(60,15,'industrial')),
 n('thermal','Thermal management',5,1,['instrumentation','materials'],'research','Build a stable operating envelope for stronger fields.',['Cooling loop, heat exchanger and branch isolation','Thermal budget in acceptance contracts'],'Complete research in powered laboratories.','Pump impeller, exchanger fans and valve action.',c(40,15,'industrial')),
 n('defense','Layered defenses',5,2,['grid','perimeter','materials'],'research','Protect a growing perimeter with a supplied defense economy.',['Wall and repair depot','Supplied sentry upgrade: ammunition recipe (1 assembly → 4 magazines / 4 s)'],'Complete research; the initial sentry retains its prototype service contract. Upgraded sentries consume magazines.','Repair arm, supplied sentry reload and impact effects.',c(40,15,'industrial')),
 n('precision','Precision research',5,3,['materials','instrumentation'],'research','Measure prepared samples to unlock precision engineering.',['Precision dossier recipe'],'Complete industrial research, then feed boards and polished crystal to the research workbench.','Precision sample fixture.',c(60,15,'industrial')),
 n('transport','Long-range transport',6,0,['modules','grid','precision'],'research','Carry material and field services between independently powered outposts.',['Freight depot and scheduled cargo carrier','Restricted-mode field conduit and route profile inspection'],'Complete research; conduit behavior uses declared loss and bend specifications.','Cargo carrier drive / dock loading cycle.',c(80,20,'industrial','precision')),
 n('coherent','Stable source arrays',6,1,['precision','thermal'],'research','Coordinate separate sources without hiding return power or drift.',['Reference-locked source and amplifier','Return-power protection and source-lock diagnostics'],'Complete research; each source must meet its locking and thermal limits.','Source locking indicator and amplifier cooling loop.',c(80,20,'industrial','precision')),
 n('pulses','Pulsed field delivery',6,2,['defense','thermal','precision'],'research','Trade peak delivery, duty cycle and heat against armored threats.',['Pulse driver and armored roaming threat encounter','Pulse energy and timing diagnostics'],'Complete research; entering the next sector introduces the new threat after defense is available.','Pulse driver charge / discharge; armored rover walk / attack.',c(80,20,'industrial','precision')),
 n('fabrication','Precision fabrication',6,3,['precision','modules','thermal'],'research','Make good parts per minute the next field-engineering reward.',['Field-assisted fabrication cell','2 polished crystal + 1 control board → 1 precision part / 8 s nominal; failures become scrap'],'Complete research; only parts that pass the cell inspection count as accepted output.','Fabrication stage, inspection scan and reject gate.',c(100,20,'industrial','precision')),
 n('photonics','Integrated photonics',7,1,['coherent','fabrication'],'research','Combine stable fields and accepted parts into integrated systems.',['Wafer patterning, optical couplers and packaged photonic modules','Systems dossier recipe'],'Complete research; produce accepted precision parts and photonic modules before making systems dossiers.','Chip carrier and optical inspection stage.',c(120,25,'industrial','precision')),
 n('distributed','Distributed infrastructure',8,0,['transport','photonics'],'research','Keep remote production districts supplied and synchronized.',['Communication relays and regional scheduling','Delay and stale-control diagnostics'],'Complete research; communication quality constrains remote automation.','Relay tracking / link indicators.',c(160,30,'industrial','precision','systems')),
 n('adaptive','Adaptive aperture control',8,1,['photonics','instrumentation'],'research','Maintain coherent delivery across a changing environment.',['Aperture sector controller','Calibration beacons and bounded adaptive control'],'Complete research; each sector performs a local calibration before joining an aperture.','Beacon sweep and sector alignment.',c(160,30,'industrial','precision','systems')),
 n('survey','Frontier observatories',8,2,['pulses','photonics'],'research','Survey safe construction corridors and track distant targets.',['Observatory and tracking receiver','Planetary aperture site survey'],'Complete research, then operate powered observatories to obtain site and target data.','Observatory scan and receiver tracking.',c(140,30,'industrial','precision','systems')),
 n('nanofab','Large-area nanofabrication',8,3,['photonics','fabrication'],'research','Scale inspected precision parts into continuous functional surfaces.',['Membrane line and metrology gantry','Sail film: 2 accepted precision parts + 1 photonic module → 1 panel / 12 s'],'Complete research; defects reduce accepted film yield.','Membrane rollers, deposition head and metrology pass.',c(180,30,'industrial','precision','systems')),
 n('aperture','Planetary aperture',9,1,['distributed','adaptive','survey'],'research','Assemble qualified sectors into a single controlled instrument.',['Aperture sector assembly','Integrated beam acceptance contract'],'Complete research; commission 4 sectors at surveyed sites, each at ≥100 useful units for 60 s with no thermal trip.','Large emitter alignment, cooling and qualification signals.',c(250,30,'industrial','precision','systems')),
 n('sail','Lightsail assembly',9,3,['nanofab'],'research','Produce and inspect the payload that gives the planetary factory a purpose.',['Sail assembly dock','100 accepted sail panels + 20 photonic modules → 1 flight sail / 120 s'],'Complete research, then pass the sail inspection with 100 accepted panels.','Sail deployment / tensioning sequence.',c(250,30,'industrial','precision','systems')),
 n('launch','Launch the lightsail',10,2,['aperture','sail'],'project','Turn the industrialized planet into a precision instrument.',['Successful launch and expedition completion'],'Proposed final acceptance: 1 inspected flight sail; 4 qualified sectors; live target tracking; ≥400 combined useful units for 120 s under declared drift, with no trips or tracking loss.','Launch cradle deployment, sail release and distant flight trail.')
];
export const technologyById=new Map(technologies.map(t=>[t.id,t]));
export function isObserved(t:Technology,world:World){return t.kind==='supplied'||!!t.observed?.(world);}
export function visibleTechnologies(world:World,full=false):Technology[]{
 if(full)return technologies;
 // Reveal two dependency steps beyond demonstrated capability. Never infer research completion.
 const visible=new Set(technologies.filter(t=>isObserved(t,world)).map(t=>t.id));
 for(let step=0;step<2;step++){
  const before=new Set(visible);
  for(const t of technologies)if(t.requires.every(id=>before.has(id)))visible.add(t.id);
 }
 visible.add('research'); // Keep the first new research capability visible as the expedition's destination.
 return technologies.filter(t=>visible.has(t.id));
}
export function technologyState(t:Technology,world:World){
 if(t.kind==='supplied')return 'Available now';
 if(t.observed)return isObserved(t,world)?'Milestone observed':t.requires.every(id=>isObserved(technologyById.get(id)!,world))?'Next objective':'Future objective';
 return 'Design proposal';
}
export function researchCost(t:Technology){return t.cost?`${t.cost.units} × ${t.cost.packs.map(p=>packs[p].name).join(' + ')} · ${t.cost.seconds} s / unit`:t.kind==='supplied'?'Expedition equipment':t.observed?'Gameplay milestone · no research cost':'Project conditions';}
