import {frontierDomain,type World,type Kind} from '../sim/world';
export interface TutorialContext {world:World;selection:string|null;cameraMoved:boolean;tool:string;build:Kind|null;diagnosticsOpen:boolean}
interface Lesson {title:string;text:string;anchor:string;focus?:{x:number;y:number};done:(c:TutorialContext)=>boolean}
const lessons:Lesson[]=[
 {title:'Welcome to your existing outpost',text:'The extractor, assembler and first field branch are already operating. We will inspect them, extend the network and install defense. The simulation keeps running. Use Next to begin.',anchor:'#map-hint',done:()=>true},
 {title:'Explore the field',text:'Wheel zooms at your cursor. Middle-drag or Alt-drag pans; WASD and arrows also pan. Click the minimap to travel. Home returns to this outpost.',anchor:'#minimap-wrap',done:c=>c.cameraMoved},
 {title:'Inspect a resource patch',text:'Click the reserve ferrous deposit at (3–7, 17–20). Its inspector shows remaining ore and offers an extractor. Existing machinery can obscure part of a deposit.',anchor:'#map-hint',focus:{x:10,y:15},done:c=>c.selection==='reserve'||c.selection==='starter'},
 {title:'Follow the production line',text:'Click the assembler near (4, 12). Its ORE IN receives visible belt packets. Two ore become one assembly in shared stock; a wire supplies 6 power.',anchor:'#map-hint',focus:{x:13,y:10},done:c=>c.selection==='e3'},
 {title:'Establish basic defense',text:'Choose Defense → Perimeter sentry. Place it near (22, 10), then Wire: power unit BUS OUT → sentry POWER IN. The sentry protects an 8-tile radius; add more as the outpost grows. This starts a 30-second warning period; sustained stray field can then agitate wildlife.',anchor:'#build-categories',done:c=>c.world.ecology.defenseReady},
 {title:'Add a phase tuner',text:'Choose Field → Phase tuner and place at (17, 12). Keep the default orientation for this walkthrough. R selects a separately drawn orientation and moves the physical ports.',anchor:'#build-categories',done:c=>c.world.entities.some(e=>e.kind==='tuner')},
 {title:'Add and power a second emitter',text:'Build a Field emitter at (20, 12). Choose Wire; click the power unit BUS OUT, then the new emitter POWER IN. Each load needs its own wire.',anchor:'#tool-power',done:c=>c.world.entities.filter(e=>e.kind==='emitter'&&e.powered).length>=2},
 {title:'Complete the second field branch',text:'Choose Field link. Connect junction D → tuner IN, then tuner OUT → second emitter IN. Click terrain for waypoints. B selects bend radius; sharp bends radiate more.',anchor:'#tool-field',done:c=>{const t=c.world.entities.find(e=>e.kind==='tuner');return !!t&&c.world.links.filter(l=>l.type==='field'&&(l.a.node===t.id||l.b.node===t.id)).length===2;}},
 {title:'Inspect problems before tuning',text:'Open Diagnostics. Each active issue explains the failure and a remedy; Locate selects and centers its object. Action failures and events remain in the history. Basic error visibility is always available.',anchor:'#issues',done:c=>c.diagnosticsOpen},
 {title:'Concentrate the field',text:'Inspect the phase tuner and adjust Relative phase. Compare On target and Off target. Enable Automatic phase control to track thermal drift; more than 32 on target damages the stationary armored frontier guardian.',anchor:'#controller',done:c=>frontierDomain(c.world)?.enabled===true&&c.world.frontier},
 {title:'Qualify your outpost',text:'Run the 20-second acceptance test, then Record qualified blueprint. If wildlife interrupts the test, inspect Diagnostics, let sentries clear nearby threats, repair damage and retry. Your layout is reusable; each new site still needs local qualification.',anchor:'#commission',done:c=>!!c.world.blueprint},
 {title:'Build a precision cell (optional)',text:'Choose Production → Fabrication cell and place it on open ground, then wire its POWER IN. In the cell inspector, assign exactly two powered emitters and a tuner, run a batch and read the useful/guard forecast before starting the 3-cycle test. This lesson is skippable.',anchor:'#build-categories',done:()=>true}
];
const key='phieldworks.tutorial.v1';
export class Tutorial {
 index=0;active=true;private cache='';private panel:HTMLElement;
 constructor(private focus:(x:number,y:number)=>void){try{const saved=JSON.parse(localStorage.getItem(key)??'null');if(saved){this.active=!saved.closed;this.index=Number.isInteger(saved.index)?Math.max(0,Math.min(lessons.length-1,saved.index)):0;}}catch{}
 this.panel=document.createElement('section');this.panel.id='tutorial';this.panel.setAttribute('aria-label','Outpost tutorial');document.body.append(this.panel);
 this.panel.addEventListener('click',e=>{const a=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-tutorial]')?.dataset.tutorial;if(a==='skip'){this.active=false;this.save();this.clear();}if(a==='next'){if(this.index===lessons.length-1){this.active=false;this.clear();}else this.index++;this.save();this.cache='';}if(a==='back'){this.index=Math.max(0,this.index-1);this.cache='';this.save();}if(a==='focus'){const f=lessons[this.index].focus;if(f)this.focus(f.x,f.y);}});
 }
 private save(){try{localStorage.setItem(key,JSON.stringify({closed:!this.active,index:this.index}));}catch{}}
 private clear(){document.querySelectorAll('.tutorial-target').forEach(el=>el.classList.remove('tutorial-target'));this.panel.hidden=!this.active;}
 replay(){this.active=true;this.index=0;this.cache='';this.save();}
 update(c:TutorialContext){this.panel.hidden=!this.active;if(!this.active)return;const l=lessons[this.index],done=l.done(c),cache=`${this.index}/${done}`;if(cache!==this.cache){this.clear();if(this.cache.split('/')[0]!==String(this.index)){const anchor=document.querySelector<HTMLElement>(l.anchor);if(anchor?.closest('aside'))anchor.scrollIntoView({block:'center'});}this.cache=cache;this.panel.innerHTML=`<div class="tutorial-heading"><span>OUTPOST ORIENTATION · ${this.index+1}/${lessons.length}</span><button data-tutorial="skip" aria-label="Skip tutorial">×</button></div><h3>${l.title}</h3><p>${l.text}</p><div class="button-row"><button data-tutorial="back" ${this.index===0?'disabled':''}>Back</button>${l.focus?'<button data-tutorial="focus">Show area</button>':''}<button class="primary" data-tutorial="next" ${!done?'disabled':''}>${this.index===lessons.length-1?'Finish':done?'Next →':'Complete step'}</button></div><small>Skip anytime with × · replay from Tutorial in the header</small>`;}
 const anchor=document.querySelector<HTMLElement>(l.anchor);if(anchor){anchor.classList.add('tutorial-target');const r=anchor.getBoundingClientRect(),w=Math.min(320,window.innerWidth-24),h=this.panel.offsetHeight;let left=r.left,top=r.bottom+12;if(top+h>window.innerHeight-12)top=r.top-h-12;if(['#map-hint','#tool-power','#tool-field'].includes(l.anchor)){const map=document.querySelector('#world')!.getBoundingClientRect();left=map.right-w-12;top=map.top+155;}this.panel.style.left=`${Math.max(12,Math.min(window.innerWidth-w-12,left))}px`;this.panel.style.top=`${Math.max(12,Math.min(window.innerHeight-h-12,top))}px`;}
 }
}
