import {readFileSync,writeFileSync} from 'node:fs';
import {technologies,researchCost} from '../src/ui/technology-data';
import {products,productById,dependencyEdges,recipeText,directUnlocks,scienceProducts} from '../src/ui/production-data';
const edges=dependencyEdges();
const key=(v:string)=>v.replace(/[:-]/g,'_');
const names=new Map([...technologies.map(t=>[`tech:${t.id}`,`${t.name} [research]`] as const),...products.map(p=>[`product:${p.id}`,`${p.name} [${p.type}]`] as const)]);
function diagram(selected:typeof edges){
 const ids=new Set(selected.flatMap(e=>[e.from,e.to]));
 return 'flowchart LR\n'+[...ids].map(id=>`  ${key(id)}["${names.get(id)}"]`).join('\n')+'\n'+selected.map(e=>`  ${key(e.from)} ${['unlocks','produces','service','prerequisite'].includes(e.relation)?'-.->':'-->'}|"${e.relation}: ${e.label}"| ${key(e.to)}`).join('\n')+'\n';
}
const totals:Record<string,number>={},dossiers:Record<string,number>={};
function expand(id:string,amount:number){const p=productById.get(id)!;if(p.type==='resource'){totals[id]=(totals[id]??0)+amount;return;}for(const i of p.ingredients)expand(i.id,amount*i.amount/p.quantity);}
for(const t of technologies)if(t.cost)for(const s of t.cost.packs){dossiers[s]=(dossiers[s]??0)+t.cost.units;expand(scienceProducts[s],t.cost.units);}
let doc=`# Complete item and equipment dependencies\n\nRevision B, 2026-09-12. Generated with \`npm run docs:progression\` from \`src/ui/production-data.ts\` and \`src/ui/technology-data.ts\`. The in-game panel uses these same records. Regenerate after editing the catalog.\n\n**${technologies.length} technologies + ${products.length} named production/capability entries = ${technologies.length+products.length} nodes, ${edges.length} typed connections.**\n\nRead solid ingredient arrows as consumed recipe inputs, dotted producer arrows as installed manufacturing equipment, unlock arrows as recipe access and service arrows as required operating infrastructure. Science edges carry research consumption; milestone edges require field evidence. Every incoming condition applies. Current entries are implemented; proposed entries are design specifications awaiting approval.\n\nThe combined diagram is available in [Mermaid source](009-full-production-graph.mmd) and in **Technology → Items & equipment → Dev: full tree → All visible connections**. The per-technology diagrams below partition the complete graph by the destination's unlocking technology, so every edge appears in one branch. External input nodes are repeated for readability.\n\n## Research-only resource audit\n\nAll research consumes ${Object.entries(dossiers).map(([id,amount])=>`${amount} ${id} dossiers`).join(', ')}. Theoretical raw inputs below recursively include nested dossiers and intermediate recipes at their stated output quantities. They assume perfect acceptance yield, batch sharing, and zero waste; they exclude construction, ammunition, final launch hardware and recovery. Fractional totals indicate shared multi-output batches, not fractional inventory items.\n\n| Raw resource | Theoretical minimum |\n| --- | ---: |\n${Object.entries(totals).map(([id,amount])=>`| ${productById.get(id)!.name} | ${amount.toLocaleString('en-US')} |`).join('\n')}\n\n## Bootstrap and upgrade contracts\n\nThe starter extractor, assembler and generator are already deployed. Keep them as production seeds; a new assembler requires assemblies that the starter assembler can make. Research foundation construction recipes unlock from first crystal and a qualified blueprint before lab deployment. Raw copper/silica/carbon are guaranteed accessible deposits unlocked by prepared materials. A producing machine is never consumed by its recipes. A machine listed in the ingredient column is recovered and consumed by an equipment upgrade; build or recover another copy if it is also required as an installed service. These differences are visible in the graph and inspector.\n\n`;
for(const t of technologies){
 const unlocked=directUnlocks(t.id),destinations=new Set([`tech:${t.id}`,...unlocked.map(p=>`product:${p.id}`)]);
 doc+=`## ${t.name}\n\n**Research prerequisites:** ${t.requires.map(id=>technologies.find(v=>v.id===id)!.name).join(' + ')||'Expedition kit'}. **Cost:** ${researchCost(t)}.\n\n${t.condition}\n\n\`\`\`mermaid\n${diagram(edges.filter(e=>destinations.has(e.to)))}\`\`\`\n\n| Unlock | Type / status | Exact recipe or acquisition | Producer | Operating requirements |\n| --- | --- | --- | --- | --- |\n`;
 for(const p of unlocked)doc+=`| ${p.name} | ${p.type} / ${p.implemented?'current':'proposed'} | ${recipeText(p)} | ${p.producer?productById.get(p.producer)!.name:'—'} | ${p.operation}${p.needs.length?' Requires: '+p.needs.map(id=>productById.get(id)!.name).join(', ')+'.':''} |\n`;
 doc+='\n';
}
writeFileSync('DevLog/009-production-dependencies.md',doc);
writeFileSync('DevLog/009-full-production-graph.mmd',`---\nconfig:\n  maxEdges: 1000\n---\n${diagram(edges)}`);
const section=`## Research schedule and concrete unlock counts\n\nThe full catalog contains ${products.filter(p=>p.type==='resource').length} resources, ${products.filter(p=>p.type==='item').length} manufactured items, ${products.filter(p=>p.type==='equipment').length} equipment/tooling entries and ${products.filter(p=>p.type==='capability').length} operating capabilities.\n\n| Research | All prerequisites | Cost / acquisition | Specific unlocked entries |\n| --- | --- | --- | --- |\n${technologies.map(t=>`| ${t.name} | ${t.requires.map(id=>technologies.find(v=>v.id===id)!.name).join(', ')||'—'} | ${researchCost(t)} | ${directUnlocks(t.id).map(p=>p.name).join('; ')} |`).join('\n')}\n`;
const path='DevLog/007-technology-tree-design.md';
writeFileSync(path,readFileSync(path,'utf8').replace(/<!-- progression:start -->[\s\S]*?<!-- progression:end -->/,`<!-- progression:start -->\n${section}\n<!-- progression:end -->`));
console.log(`Generated ${technologies.length+products.length} nodes and ${edges.length} connections across ${technologies.length} branch diagrams.`);
