import {writeFileSync} from 'node:fs';
import {technologies} from '../src/ui/technology-data';
const subjects:Record<string,string>={
outpost:'Compact extraction-and-assembly production cell: drill at left, short ore belt, articulated assembly arm at right, copper turbine behind. Three machines on one tidy industrial foundation.',
fieldcraft:'One four-port ceramic junction linked to a small phase carriage and angled field emitter; copper plumbing and cyan connector rings make the branch legible.',
perimeter:'A squat twin-barrel perimeter sentry with cream ceramic hood, horizontal cyan sensor slit and bolted dark pedestal. No firing effects.',
frontier:'A broken mineral-armored guardian shell beside an opened passage toward pale blue crystal, a small coherent emitter at the edge. Clearly an environmental achievement, not a new machine.',
crystal:'A harvested pale blue precision crystal in a steel transport cradle beside a compact drill head. Distinct crystal silhouette dominates.',
qualification:'A rugged commissioning console beside a folded modular installation plan and a physical green acceptance lamp. No letters or checkmark UI; this is an engineering achievement.',
research:'A ceramic research workbench sample-transfer arm beside a compact covered laboratory carousel with six sample sockets and a rugged ochre industrial dossier cartridge.',
logistics:'A clear Y-shaped conveyor splitter with visible hinged gate and two short belts, plus paired low underground entrance and exit hoods.',
instrumentation:'A freestanding industrial monitor with a dark cyan trace screen and a tethered branch probe clamped around a field connector. No lettering or legible digits.',
grid:'A heavy substation with copper busbars, ceramic insulators, a visible breaker and two utility poles. Strong electrical distribution silhouette.',
materials:'A horizontal ceramic polishing drum and feed rollers beside four prepared products: polished crystal, steel billet, copper conductor and ceramic substrate.',
modules:'Two compact prefabricated industrial cells joined by chunky keyed service connectors, a lifting frame over one module. Modular construction, no humanoid workers.',
thermal:'A broad finned heat exchanger with twin fans, a copper pump and closed coolant pipes, cool teal reservoir. No fire.',
defense:'A supplied twin-barrel sentry with a distinct side magazine rack, low wall section and a small repair-depot arm. Visibly upgraded perimeter hardware.',
precision:'A precision sample fixture with polished crystal held between micrometer jaws, a control board and a slim teal precision dossier cartridge.',
transport:'A short rugged autonomous cargo carrier docking at a freight station with a loading arm and a sealed field-conduit service port. No tracks extending outside composition.',
coherent:'Two matched cylindrical sources sharing a narrow ceramic reference spine, separate copper amplifier heatsink, small return-power protection block. Symmetric stable source array.',
pulses:'A pulse driver: bank of three squat capacitor cylinders, heavy switching bridge and single field output aperture. Ochre charge indicator. No giant laser beam.',
fabrication:'An enclosed precision fabrication cell with a horizontal inspection stage, optical processing head and separate accepted-part tray and reject chute.',
photonics:'An open wafer carrier under a precision patterning head, with a small packaged photonic module and two tiny ceramic optical couplers in foreground.',
distributed:'Two communications relay masts flanking a compact cargo scheduling terminal, directional dishes facing different districts, subtle cyan link indicators.',
adaptive:'A sector controller cabinet with three small calibration beacons surrounding a segmented hexagonal emitter tile, one beacon emitting a restrained cyan ring.',
survey:'A squat observatory with a rotating open dome and large tilted tracking receiver, small survey tripod beside it. Clear surveying silhouette.',
nanofab:'A wide membrane production line: paired tension rollers stretch a thin iridescent film beneath a metrology gantry and deposition head. Film is continuous and flat.',
aperture:'A large hexagonal aperture sector made of seven aligned ceramic emitter facets, copper cooling manifold around its edge and small sector control pedestal.',
sail:'A lightsail assembly dock with four tension arms holding an ultrathin silvery square membrane and compact corner rigging. Industrial manufacturing context.',
launch:'A deployed delicate square lightsail separating above its release cradle, four distant small aperture sectors beneath it aligned upward. Compact emblem-like scene of successful launch, no rocket.'
};
const style='Use case: stylized-concept. Asset type: PHIELDWORKS technology node illustration, one square 1024x1024 image. Fixed orthographic oblique top-down camera, upper-left soft light. Chunky readable painterly 3D industrial game art, weathered off-white ceramic, charcoal steel, exposed copper, restrained cyan indicators. Single centered coherent composition filling 75 percent of canvas with generous empty margin. Dark uniform teal #101b1d backdrop, no scene horizon, no text, labels, numbers, logos, border, watermark or UI. Distinct silhouette readable at 48 and 96 pixels. This is a technology illustration, not a sprite atlas.';
const jobs:any[]=technologies.map(t=>({id:`tech-${t.id}`,technology:t.id,title:t.name,category:'technology',path:`assets/technology/nodes/${t.id}-v1.png`,columns:1,rows:1,prompt:`${style} Subject: ${subjects[t.id]} Gameplay meaning: ${t.summary}`}));
const root=process.cwd();
const motion=(id:string,ref:string,action:string,cols=4,rows=4)=>jobs.push({id,category:'animation',path:`assets/animations/candidates/${id}.png`,columns:cols,rows,reference:`${root}/${ref}`,prompt:`Use case: precise-object-edit. Asset type: PHIELDWORKS animation atlas. Reference image is identity reference ONLY, preserve its exact machine or creature identity, material palette and anatomy. Produce ONE square sprite sheet with exactly ${cols} columns and ${rows} rows, ${cols*rows} complete subjects. ${rows===4?'ROWS are four physically turned ground-plane orientations: original, 90, rear 180, 270 degrees. COLUMNS are chronological animation frames of the SAME orientation.':'All cells use the SAME original camera and orientation; read frames left-to-right then top-to-bottom chronologically.'} ${action} Fixed orthographic oblique top-down camera and upper-left lighting. LOCK static chassis/base, scale, anchor, connectors and background across every motion frame; move only named mechanisms. Center each subject in its equal cell with 20 percent padding and completely empty gutters; nothing crosses cell boundaries. Physically redraw other directions, never rotate or mirror a flat image. True transparent RGBA background, no painted checkerboard, no matte, no cast ground shadow. No text, numerals, labels, borders, logos, watermark, smoke, flash or beam effects.`});
motion('extractor-severe-cycle-v1','assets/states/extractor-condition-v1.png','Use severely damaged third-row identity: cracked ceramic and exposed copper persist identically in every frame, functional drill survives. Four drill phases: raised, halfway down, fully down, halfway raised. Housing never moves.');
motion('assembler-light-cycle-v1','assets/states/assembler-condition-v1.png','Use lightly damaged second-row identity with one chipped corner and scuffed panel. Four phases: arm raised over input, grip at tray, press lowered on work stage, arm lifted returning. Damage locations never change.');
motion('assembler-severe-cycle-v1','assets/states/assembler-condition-v1.png','Use severely damaged third-row identity: missing side panels, cracked ceramic and exposed internals, working core arm. Four phases: reach input, grip, press on stage, lift returning. Exact damage remains across frames.');
motion('generator-cycle-v1','assets/world/power-unit-turnaround-v2.png','Four phases of exposed rotor and front cooling fan rotation. Ceramic cylindrical housing and copper bus terminals stay completely fixed. Unlit lamp recesses; illumination added in runtime.');
motion('sentry-fire-v1','assets/world/perimeter-sentry-v1.png','Four recoil phases: twin barrels extended, both recoiled a short distance, halfway returned, fully extended. Pedestal and head aim stay fixed. No firing flashes or bullets.');
jobs.push({id:'transport-items-v1',category:'items',path:'assets/animations/candidates/transport-items-v1.png',columns:2,rows:2,prompt:'Use case: stylized-concept. PHIELDWORKS inventory sprite atlas, square exact 2x2 equal cells. Top left rusty ferrous ore nugget; top right bolted steel-and-ceramic industrial assembly with copper winding; bottom left pale blue crystal shard in metal cradle; bottom right bent metal, cracked ceramic and short copper coil as compact scrap bundle. Fixed oblique camera, upper-left light, bold distinct silhouettes at 12–32 px. Center each item with 20% empty margins. True transparent RGBA, no painted checkerboard, no matte, no cast shadow, text, labels, borders or glow.'});
motion('guardian-idle-v1','assets/sprites/armored-frontier-organism-v1.png','Four chronological breathing frames: rest, slight torso rise, expanded armored thorax, settling. Anchored angular dark rock plates and amber organic joints, fixed planted legs. No walking or root translation.',2,2);
motion('guardian-collapse-v1','assets/sprites/armored-frontier-organism-v1.png','Four chronological death frames: brace and crack, legs buckle, mineral armor collapses inward, static low rubble remains. Non-gory stone creature. Single one-shot sequence; keep foundation center fixed.',2,2);
motion('crawler-attack-v1','assets/world/investigator-crawler-v1.png','Four chronological attack phases: brace on rear legs, lift front limbs, short forward strike with forelimbs, recoil to brace. Same six-legged mineral-plated crawler anatomy, body center stays within cell. No projectiles.');
motion('crawler-death-v1','assets/world/investigator-crawler-v1.png','Four chronological non-gory death phases: body crouches, legs buckle, shell settles low, static collapsed remains. One-shot sequence per direction; retain identical anatomy and scale.');
writeFileSync('assets/technology/generation-pass-03.json',JSON.stringify({date:'2026-09-13',tool:'built-in image_gen',jobs},null,2)+'\n');console.log(`${jobs.length} jobs prepared`);
