import {chromium} from '@playwright/test';
import {writeFileSync} from 'node:fs';
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
await page.addInitScript(()=>localStorage.setItem('phieldworks.tutorial.v1',JSON.stringify({closed:true,index:0})));
const base=process.env.PHIELDWORKS_REVIEW_URL??'http://127.0.0.1:5175';
await page.goto(base);await page.locator('#runtime-status').filter({hasText:'ONLINE'}).waitFor();
const point=async(x,y)=>{const p=await page.evaluate(([x,y])=>window.phieldworks.screen(x,y),[x,y]);await page.mouse.click(p.x,p.y);};
await page.locator('#pause').click();await point(4.5,9.5);await page.locator('[data-route-edit]').click();await point(7,9.5);await point(7,10.5);
await page.screenshot({path:'test-results/route-edit-active.png'});
await page.keyboard.press('Escape');await page.locator('#pause').click();await page.locator('#issues').click();await page.waitForTimeout(2200);await page.locator('#copy-report').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/diagnostics-visible-trend.png'});
const fixture=await page.evaluate(async()=>{const m=await import('/src/sim/world.ts');const w=m.createWorld();const failure=m.place(w,'reference',17,18);if(failure)throw Error(failure);const target=w.entities.at(-1);const error=m.connect(w,'power',{node:'e1',port:0},{node:target.id,port:0});if(error)throw Error(error);localStorage.setItem('fieldworks.save.v1',m.serialize(w));return target.id;});
await page.locator('#close-issues').click();await page.locator('#load').click();await page.waitForTimeout(350);await page.locator('#issues').click();await page.locator('#issue-filter').selectOption('error');await page.waitForTimeout(350);await page.locator('#ledger').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/power-overload-review.png'});
const overload=await page.evaluate(()=>({stats:window.phieldworks.stats(),powered:window.phieldworks.snapshot().entities.map(e=>({id:e.id,kind:e.kind,powered:e.powered}))}));
await page.goto(base+'/assets/states/index.html');await page.locator('#review-status').filter({hasText:'9/9'}).waitFor();await page.locator('#pause-preview').click();
const states=[];for(const [preset,rotation] of [['off','0'],['light','1'],['severe','2'],['wreck','3'],['trip','0']]){await page.locator(`[data-preset=${preset}]`).click();await page.locator('#rotation').selectOption(rotation);await page.waitForTimeout(100);states.push({preset,rotation,cards:await page.locator('[data-kind]').evaluateAll(es=>es.map(e=>({...e.dataset,label:e.querySelector('.state-label').textContent})))});await page.screenshot({path:`test-results/state-${preset}-${rotation}.png`,fullPage:true});}
await page.goto(base);await page.locator('#runtime-status').filter({hasText:'ONLINE'}).waitFor();
const renders=await page.evaluate(async()=>{const {Renderer}=await import('/src/renderer.ts'),m=await import('/src/sim/world.ts');const c=document.createElement('canvas');c.style.cssText='width:1100px;height:700px';document.body.append(c);const r=new Renderer(c,{rotation:0,diagonal:false,radius:.5,waypoints:[],selected:null,build:null,tool:'select',pending:null,overlay:true,grid:false,mouse:null,panX:0,panY:0,zoom:.55});const rows=[];for(const count of [40,80,120]){const w=m.createWorld();while(w.entities.length<count){const i=w.entities.length;w.entities.push(m.newEntity('sentry',2+i%20*3,22+Math.floor(i/20)*2,`e${i+100}`));}const times=[];for(let i=0;i<65;i++){const t=performance.now();r.draw(w);if(i>=15)times.push(performance.now()-t);}times.sort((a,b)=>a-b);rows.push({machines:count,samples:50,warmup:15,medianMs:times[25],p95Ms:times[47],note:'CPU canvas submission only; excludes GPU presentation'});}c.remove();return rows;});
writeFileSync('test-results/visual-review.json',JSON.stringify({fixture,overload,states,renders},null,2));console.log(JSON.stringify({overload:overload.stats.overload,powered:overload.powered,renders}));await browser.close();
